// Hello there
// test 2
/**
 * SubscriberManagementAPI
 * The SubscriberManagementAPI, part of ViewBid.ca Auction application provides functionalities to manage subscriber data.  Specifically, it supports creating, updating, retrieving, and deleting subscriber records through standard CRUD operations. Additionally, it offers specialized example methods for administrative tasks such as calculating the number of active (\"good\") subscribers and automated cleanup of inactive subscriber accounts (unused for 60 days or more). 
 *
 * The version of the OpenAPI document: 25.03.21d
 * Contact: willdev@viewbid.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Subscribers { 
    /**
     * 
     */
    id?: string;
    /**
     * 
     */
    createdon?: string;
    /**
     * 
     */
    createdby?: string;
    /**
     * 
     */
    updatedon?: string;
    /**
     * 
     */
    updatedby?: string;
    /**
     * 
     */
    deletedon?: string;
    /**
     * 
     */
    deletedby?: string;
    /**
     * 
     */
    accountsid?: string;
    /**
     * 
     */
    subscriptionkey?: string;
}

